### ISSUE TITLE
Get-CheckPointHosts only return the first 200 objects

### ISSUE THREAD

**Issue by urskog84** [tkoopman/psCheckPoint#25]
Get-CheckPointHosts only return the first 200 objects.
you need to loop through all objects in the database.

and increasing the offer value foreach loop.

https://sc1.checkpoint.com/documents/latest/APIs/index.html#web/show-hosts~v1.1

**Comment by tkoopman** [comment]
-Limit and -Offset options already exist so that you can create your own loop.
If you run `Get-CheckPointHosts | gm` To, From & Total fields are returned as per the Web API.

This was left this way as it is normally better to only get what you need at a time, especially in large environments. That said I can add a -All option to all those commands that will do the looping for you.

I have added this option to v0.7.8 which is now released. Both manual looping and this new looping have been testing with 9000+ objects.

-Limit can still be used with -All object to change the number of objects retrieved each request.
